assets/css/theme.css: less/blog-mixins.less less/blog.less less/code.less less/layout.less less/lists.less less/mixins.less less/pager.less less/pagination.less less/prettify.less less/reset.less less/theme.less less/thumbnails.less less/type.less less/variables.less
	lessc less/theme.less > assets/css/theme.css

